---
# --- Scanning the URL in the Sandbox ---

- name: Ensure results directory exists (on remote machine)
  file:
    path: /tmp/results
    state: directory
  delegate_to: server2 
  tags: ["docker", "sandbox", "scan"]

- name: Deploy the script in the container (via template)
  template:
    src: script.sh.j2
    dest: /tmp/scan.sh
    mode: '0755'
  delegate_to: server2
  tags: ["docker", "sandbox", "scan"]

- name: Copy the script into the container
  shell: docker cp /tmp/scan.sh qrcode_sandbox:/tmp/scan.sh
  delegate_to: server2
  tags: ["docker", "sandbox", "scan"]

- name: Start the scan in the container
  shell: docker exec qrcode_sandbox bash /tmp/scan.sh "{{ url_a_tester }}" > /tmp/results/{{ id_container }}.txt
  delegate_to: server2
  tags: ["docker", "sandbox", "scan"]

- name: Repatriate the result to the control node (Ansible machine)
  fetch:
    src: /tmp/results/{{ id_container }}.txt
    dest: /root/containers/EvilQRcode/QRTool/SandBoxGenerator/results/{{ id_container }}.txt
    flat: yes
  delegate_to: server2
  tags: ["docker", "sandbox", "scan"]
