
services:
  web:
    build: .
    container_name: badserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./emails.txt:/var/www/html/emails.txt
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true